// <auto-generated />
using System;
using HotelReservationWeb.Data.Client_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReservationWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606224042_InitialDeploy")]
    partial class InitialDeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("FacilityAvailabilityAvailabilityId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("FacilityAvailabilityAvailabilityId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("VenueId");

                    b.ToTable("tblBooking");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ActivityLogId");

                    b.ToTable("tblActivityLogs");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext");

                    b.HasKey("BuildingId");

                    b.ToTable("tblBuildings");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HomeIndexCategory")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExploreHighlight")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("FacilityId");

                    b.ToTable("tblFacilities");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.FacilityAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("BookedSlots")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("VenueId");

                    b.HasIndex("FacilityId", "RoomTypeId", "VenueId", "Date")
                        .IsUnique();

                    b.ToTable("tblAvailability");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.FacilityImage", b =>
                {
                    b.Property<int>("FacilityImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FacilityImageId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FacilityImageId");

                    b.HasIndex("FacilityId");

                    b.ToTable("tblFacilityImages");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.RoomImage", b =>
                {
                    b.Property<int>("RoomImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoomImageId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("tblRoomImages");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FacilityId");

                    b.ToTable("tblRoomTypes");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblStaff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hotel.com",
                            IsSuperAdmin = true,
                            PasswordHash = "$2a$11$Hen47zE3WX3U70QkLekeMewY1FrZ3BIWCNvwHiyZw14YpvuxlBVmW"
                        });
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("CapacityMax")
                        .HasColumnType("int");

                    b.Property<int>("CapacityMin")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Feature1")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature2")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExploreHighlight")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VenueCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VenueId");

                    b.HasIndex("FacilityId");

                    b.ToTable("tblVenues", (string)null);
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Models_Client.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("VenueId");

                    b.ToTable("tblFavorites");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Models_Client.HotelClient", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClientId");

                    b.ToTable("tblHotelClient");
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Models_Client.HotelClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.FacilityAvailability", null)
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityAvailabilityAvailabilityId");

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.RoomType", "Room")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Room");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.FacilityAvailability", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Facility", "Facility")
                        .WithMany("Availabilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.RoomType", "RoomType")
                        .WithMany("Availabilities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Venue", "Venue")
                        .WithMany("Availabilities")
                        .HasForeignKey("VenueId");

                    b.Navigation("Facility");

                    b.Navigation("RoomType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.FacilityImage", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Facility", "Facility")
                        .WithMany("FacilityImages")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.RoomImage", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Model_Staff.RoomType", "RoomType")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.RoomType", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Building", "Building")
                        .WithMany("RoomTypes")
                        .HasForeignKey("BuildingId");

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Facility", "Facility")
                        .WithMany("RoomTypes")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Venue", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Facility", "Facility")
                        .WithMany("Venues")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Models_Client.Favorite", b =>
                {
                    b.HasOne("HotelReservationWeb.Models.Models_Client.HotelClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId");

                    b.HasOne("HotelReservationWeb.Models.Model_Staff.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.Navigation("Client");

                    b.Navigation("RoomType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Building", b =>
                {
                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Facility", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("FacilityImages");

                    b.Navigation("RoomTypes");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.FacilityAvailability", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.RoomType", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("HotelReservationWeb.Models.Model_Staff.Venue", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
